# Generated by Django 3.2.7 on 2021-09-10 14:31

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='캠페인')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
            ],
            options={
                'verbose_name': '캠페인',
                'verbose_name_plural': '캠페인',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='이름')),
                ('description', models.CharField(max_length=100, verbose_name='설명')),
                ('type', models.CharField(choices=[('PERCENT', '퍼센트'), ('VALUE', '값')], default='CASH', max_length=10, verbose_name='타입')),
                ('value', models.DecimalField(decimal_places=2, default=0.0, max_digits=7, validators=[django.core.validators.MinValueValidator(0)], verbose_name='값')),
                ('weekday', models.SmallIntegerField(blank=True, choices=[(0, '월'), (1, '화'), (2, '수'), (3, '목'), (4, '금'), (5, '토'), (6, '일')], validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(6)], verbose_name='요일')),
                ('time', models.SmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(24)])),
                ('days', models.SmallIntegerField(default=7)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='생성일')),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coupons', to='coupon.campaign')),
            ],
            options={
                'verbose_name': '쿠폰',
                'verbose_name_plural': '쿠폰',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='CouponUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(default=django.utils.timezone.now, verbose_name='생성일')),
                ('expired_at', models.DateField(default=django.utils.timezone.now, verbose_name='만료일')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='사용일')),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coupon.coupon', verbose_name='쿠폰')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='유저')),
            ],
            options={
                'verbose_name': '쿠폰유저',
                'verbose_name_plural': '쿠폰유저',
            },
        ),
    ]
