# Generated by Django 3.2.7 on 2021-09-10 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='campaign',
            table='coupon_campaign',
        ),
        migrations.AlterModelTable(
            name='coupon',
            table='coupon',
        ),
        migrations.AlterModelTable(
            name='couponuser',
            table='coupon_user',
        ),
    ]
